Stellantis_Djz/GA_UEP/urls.py
from django.urls import path
#from GA_UEP.views import CrudView
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from .views import *
from django.views.decorators.csrf import csrf_exempt
app_name = "GA_UEP"
urlpatterns = [
    path("", views.index, name="indexx"),
    path("loginn/", views.login_view, name="login"),
    path("logoutt/", views.logout_view, name="logout"),
    path("api/get_réf/", views.get_réf, name='get_réf'),
    path("crud/", CrudView.as_view(), name='crud_ajax'),
    path("crossdock/", CrudCrossDock.as_view(), name='cross_dock'),
    path("crossdock/historique/Search", views.SearchHCD, name='cross_dock_HSearch'),
    path("Magdebord/", CrudMagDebord.as_view(), name='Mag_debord'),
    path("FLC/", CrudFLC.as_view(), name='FLC_A'),
    path("update/CD", UpdateAler.as_view(), name="update_CD"),
    path("update/CD/Histo", UpdateAlerHisto.as_view(), name="update_CD_Histo"),
    path("update/FLC", UpdateAlerFLC.as_view(), name="update_FLC"),
    path("update/DB", UpdateAlerDB.as_view(), name="update_DB"),
    path("create/", CreateCrudInv.as_view(), name='create'),
    path('delete/', DeleteCrudInv.as_view(), name='delete'),
   
    path("Dashboard", views.Dashboard, name="Dashboard"),
    path("Error", views.Error, name="Error"),

    #Dashboards des alertes url
    path("Dashboard/KPIS", KPIS.as_view(), name="KPIS"),
    path("Dashboard/SUIVIAL", views.suiviAlertes, name="suiviAlertes"),

    path("Dashboard/EVALAL", views.evolutionAlertes, name="evolutionAlertes"),
    path("Dashboard/TOP10", views.Top10Alertes, name="Top10Alertes"),
    #Dashboards stock déébord url
    path("Dashboard/ESdebord", views.ESdebord, name="ESdebord"),
    path("Dashboard/NBJdebord", views.NBJdebord, name="NBJdebord"),
    path("Dashboard/Top5sortie", views.Top5sortie, name="Top5sortie"),
    path("Dashboard/Top5entree", views.Top5entree, name="Top5entree"),

#gestion de stock ---------------------------------------------
    path("Magdebord/stcokDebord", CrudStock.as_view(), name='Gestion_SDB'),

    path("search-items", csrf_exempt(views.search_items), name="search-items"),

    path("ajouteritem/", ajouteritem.as_view(), name='ajouteritem'),

    path("updateitems/", updateitems.as_view(), name='updateitems'),
    
    path("vidertravée/", vidertravée.as_view(), name='vidertravée'),

    path("ESStockdébord/", ESStockdébord.as_view(), name='ESStockdébord'),
    
    path("api/get_réfS/", views.get_réfS, name='get_réfS'),
    path("api/get_réfT/", views.get_réfT, name='get_réfT'),
    path("exportstockdebord/", views.exportstockdebord, name='exportstockdebord'),
    
    
    path("exporterEE/", views.exporterEE, name='exporterEE'),
    path("exporterSS/", views.exporterSS, name='exporterSS'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Stellantis_Djz/Stellantis_Djz/urls.py
from GA_UEP import views
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('GA_UEP.urls')),
    
    
    

    
]

Stellantis_Djz/GA_UEP/forms.py
from django import forms
from .models import Stock


class StockForm(forms.ModelForm):
   class Meta:
     model = Stock
     fields = ['Reference', 'Nb_bacs', 'Travee_debord']

Stellantis_Djz/GA_UEP/views.py
from datetime import timedelta
from typing import List
#from typing_extensions import Annotated
from django import template
from django.contrib.auth import authenticate, login, logout
from django.db.models.aggregates import Max ,Sum
from django.db.models.base import Model
from django.db.models.expressions import When
from django.http import response
from . models import Alertes, Inventaire, Map, MapStock, Membership, Stock, ESStock
from django.http import HttpResponseBadRequest, HttpResponseRedirect, Http404, request, HttpResponse
from django.urls import reverse
from django.db.models import Count, query, Func, CharField,Value
from django.core import serializers
from django.http.response import HttpResponse, JsonResponse
from datetime import date, datetime, timedelta, time
from django.http import JsonResponse
from django.contrib import messages
import json
from django.views.generic import TemplateView, ListView, View
from django.contrib.sessions.models import Session
from django.db.models import Q, F, DurationField, ExpressionWrapper, Avg, FloatField
from django.template import Context, context
from django.core.mail import EmailMessage
from django.conf import settings
from django.template.loader import render_to_string
from django.core.mail import send_mail
from django.db.models.functions import TruncDate
from django.utils.dateparse import parse_datetime
import statistics
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import StockForm
from django.shortcuts import render, redirect
import xlwt
#-----------------------------------------------------------------------------------------------------
# Create your views here.-----------------------------------------------------------------------------
# data we use ----------------------------------------------------------------------------------------
today = date.today()
now = datetime.now()
map_all = Map.objects.all() # all columns from Map
d1 = today.strftime("%d/%m/%Y") # la date 
n1 = now.strftime("%H:%M:%S")# l'heure
#autocomplete  bordkit --------------------------------------------------------------------------------------
def get_réf(request):
  if request.is_ajax():
    q = request.GET.get('term', '')
    réfs = Map.objects.filter(Map_Réference__icontains=q)
    results = []
    for pl in réfs:
      réfs_json = {}
      réfs_json = pl.Map_Réference
      results.append(réfs_json)
    data = json.dumps(results)
  else:
    data = 'fail'
  mimetype = 'application/json'
  return HttpResponse(data, mimetype)
                                          
#crud  pour Borkit page view with ajax -----------------------------------------------------------------------
class CrudView(TemplateView): 
    template_name = 'BordKit.html'
    def get_context_data(self, **kwargs):
        person = self.request.user.username 
        c = Inventaire.objects.filter(Date=datetime.now().strftime("%d/%m/%Y"), name=person).count()
        if c == 0:
            k = Inventaire(Reference="--",
                           Nombre_De_Bac="--", Zone_De_Kit="--",
                           SM_Csc="--", Date=datetime.now().strftime("%d/%m/%Y"), heure=now.strftime("%H:%M:%S"), name=person, SDate=datetime.now())
            k.save()
        context = super().get_context_data(**kwargs)
        context['invs'] = Inventaire.objects.filter(
            Date=datetime.now().strftime("%d/%m/%Y"), name=person).order_by('-heure')

        return context

class CreateCrudInv(View):
    def get(self,request):
        global nm_input,hc
        réf_inv = request.GET.get('Reference', None)
        nbr_bac_inv = request.GET.get('Nombre_De_Bac', None)
        nm_input = request.GET.get('name', None)
        dc = request.GET.get('Date', None)
        hc = request.GET.get('heure', None)
        filt2 = Inventaire.objects.filter(name=nm_input)
        for j in filt2:
            nm = j.name
        filt1 = Map.objects.filter(Map_Réference=réf_inv)
        if not filt1:
            msg="Réference Non Trouvé"
            data={'msg':msg}
            return JsonResponse(data)
        else:
            for i in filt1:
                zkit = i.Map_PDC
                cvm = i.CVM  
                condi = i.condi
                uc = i.condiQ
            #add data to alertes
            obj = Inventaire.objects.create(
                Reference = réf_inv,
                Nombre_De_Bac = nbr_bac_inv,
                Zone_De_Kit= zkit,
                SM_Csc=cvm,
                Date=dc,
                heure=hc,
                name=nm,
                )
            inv = {'id': obj.id, 'Reference': obj.Reference,
                    'Nombre_De_Bac': obj.Nombre_De_Bac,
                    'Zone_De_Kit': obj.Zone_De_Kit,
                    'SM_Csc':obj.SM_Csc,
                    'Date': obj.Date,
                    'heure': obj.heure,
                    'name': obj.name
                    }
            data = {
                    'inv':inv
                }
        # convert inventaire to alerte
        if filt1:
            filt3 = Membership.objects.filter(person=nm_input)
            for j in filt3:
                moniteur = j.Moniteur
            al = Alertes(
                Reference=réf_inv,
                Nombre_De_Bac=nbr_bac_inv,
                Zone_De_Kit=zkit,
                SM_Csc=cvm,
                Code_condi=condi,
                QTe_Uc=uc,
                Date=dc,
                heure=hc,
                Moniteur= moniteur,
                )
            al.save()
            return JsonResponse(data)


class DeleteCrudInv(View):
    def get(self, request):
        id1 = request.GET.get('id', None)
        Inventaire.objects.get(id=id1).delete()
        data = {
            'deleted': True
        }
        return JsonResponse(data)


# crud view pour le crossDock -----------------------------------------------------------------------------

class CrudCrossDock(TemplateView):
    template_name = 'CrossDock.html'
    def get_context_data(self, **kwargs):   
        context = super().get_context_data(**kwargs)
        context['alertes'] = Alertes.objects.filter(
            Q(Date=datetime.now().strftime("%d/%m/%Y"), ) | Q(HFA='....') | Q(HFA=None)).order_by('-heure')
        context['T_A_NT'] = Alertes.objects.filter(
            Q(Date=datetime.now().strftime("%d/%m/%Y")) & (Q(statut='Alerte_CK')
            | Q(statut=None))).count()
        context['Train'] = Alertes.objects.filter(
            statut='Train', Date=datetime.now().strftime("%d/%m/%Y")).count()
        context['Adebord'] = Alertes.objects.filter(
            statut__in=('A_Débord', 'Alerte_DEB'), Date=datetime.now().strftime("%d/%m/%Y")).count()
        context['Livré'] = Alertes.objects.filter(
            statut='Livré', Date=datetime.now().strftime("%d/%m/%Y")).count()
        context['AT'] = Alertes.objects.filter(
            statut='A_Tranche', Date=datetime.now().strftime("%d/%m/%Y")).count()
        context['AR'] = Alertes.objects.filter(
            statut='A_Remorque', Date=datetime.now().strftime("%d/%m/%Y")).count()

        context['TA'] = Alertes.objects.exclude(statut='Train').filter(                                                                    
            Date=datetime.now().strftime("%d/%m/%Y")).count()

        context['FLC'] = Alertes.objects.filter(
            statut='FLC', Date=datetime.now().strftime("%d/%m/%Y")).count()
        context['FLC_T'] = Alertes.objects.filter(
            statut='FLC_T', Date=datetime.now().strftime("%d/%m/%Y")).count()
        return context

class UpdateAler(View):
    def get(self, request):
        id1 = request.GET.get('id', None)
        st = request.GET.get('statut', None)
        cmnt = request.GET.get('Commenataire', None)
        shif = request.GET.get('Shifts', None)
        grp = request.GET.get('Groupes', None)
        #h = now.strftime("%H:%M:%S")
        obj = Alertes.objects.get(id=id1)
        obj.statut = st
        obj.Commenataire = cmnt
        obj.Shifts = shif
        obj.Groupes = grp
        if(st == "Livré" or st == "Train" or st == "A_Tranche" or st == "A_Remorque"):
            obj.HFA = datetime.now().strftime("%H:%M:%S")
        else:
            obj.HFA = '....'
        obj.save()
        #reponse pour agent Bord de Kit 
        h= Alertes.objects.filter(id= id1)
        for i in h:
            global réfj
            heurej = i.heure
            réfj = i.Reference
        g = Inventaire.objects.get(heure=heurej, Reference=réfj)
        g.statut=st
        g.save()
       
        alt = {'id': obj.id, 'statut': obj.statut, 
               'Commenataire': obj.Commenataire, 'Shifts': obj.Shifts,
               'Groupes': obj.Groupes,'HFA':obj.HFA }
        data = {
            'alt': alt
            
        }
        return JsonResponse(data)



# crud view pour Cross Dock Historique------------------------------------------------------------------ 
# pour la recherche sur les references Alertes dans l'historique 
def SearchHCD(request):
    #total kpi--------------------------------
    HKpi= Context()
    HKpi['T_A_NT'] = Alertes.objects.filter(
        (Q(statut='Alerte_CK') | Q(statut=None))).count()
            
                                               
    HKpi['Train'] = Alertes.objects.filter(statut='Train').count()
        
    HKpi['Adebord'] = Alertes.objects.filter(
        statut__in=('A_Débord', 'Alerte_DEB')).count()

    HKpi['Livré'] = Alertes.objects.filter(statut='Livré').count()

    HKpi['AT'] = Alertes.objects.filter(statut='A_Tranche').count()
        
    HKpi['AR'] = Alertes.objects.filter(statut='A_Remorque').count()
        
    HKpi['TA'] = Alertes.objects.filter(statut__in=('Alerte_CK', 'A_Débord', 'Alerte_DEB',
                                                    'Livré', 'A_Tranche', 'A_Remorque', 'FLC', 'FLC_T')
                                        ).count()
    HKpi['FLC'] = Alertes.objects.filter(statut='FLC').count()

Stellantis_Djz/GA_UEP/templates/ESStockdébord.html
{% extends "layout.html" %}
{% load static %}

{% block body %}
<div class="text-center mt-1">
    <h3 class="display-6">Historique Magasin Débord </h3>
</div>


<div class="container">
    <div class="row">
        <div class="col">
            <div class="btn-group" role="group" aria-label="Basic example">

                <a class="btn btn-info" role="button" href="{% url 'GA_UEP:Gestion_SDB' %}"><i
                        class="fas fa-store fa-sm text-white-50"></i>&nbsp;Magasin débord</a>

            </div>
        </div>
        
        <div class="col-3">
            <div class="row justify-content-md-center">
                <div class="alert alert-success fas fa-arrow-left fa-store" role="alert">
                   {{entr.Nb_bacs__sum}}  : bacs/J
                </div>
            </div>
        </div>
        <div class="col-3">
            <div class="row justify-content-md-center">
                <div class="alert alert-danger fas fa-arrow-right " role="alert">
                   {{sort.Nb_bacs__sum}} : bacs/J
                </div>
            </div>
        </div>
        <div class="col">
            <div class="btn-group" role="group" aria-label="Basic example">
                <a class="btn btn-success  d-none d-sm-inline-block" role="button" href="{% url 'GA_UEP:exporterEE' %}" ><i
                        class="fas fa-file-download fa-sm text-white-40"></i>&nbsp; les entrées</a>

                <a class="btn btn-danger  d-none d-sm-inline-block" role="button" href="{% url 'GA_UEP:exporterSS' %}" ><i
                        class="fas fa-file-download fa-sm text-white-40"></i>&nbsp; les sorties</a>



            </div>
        </div>
    </div>
</div>





<!--  table magasin débord-->


<div class="card">
    <div id="result" class="card-body">
        <div class="form-group">
            <input type="text" class="form-control" id="searchField" placeholder=" Rechercher...">
        </div>
        <div class="table-responsive table mt-2" id="dataTable-1" role="grid" aria-describedby="dataTable_info">

            <div class="app-table">
                <table class="table table-sm table-hover" id="histotableData" style="color: #33313b;">
                    <thead>
                        <tr>
                            
                            <th>Emplacement SM</th>
                            <th>Réference</th>
                            <th>Nombre de Bac</th>
                            <th>Date d'éntrée</th>
                            <th>Travée débord</th>
                            <th>code condi</th>
                            <th>Qt piéce/UC</th>
                            <th>Appro</th>
                            <th>Fournisseur</th>
                            <th>CMJ</th>
                            <th>FDS</th>
                            <th>Date de sortie</th>
                        </tr>
                    </thead>
                    {% if essstocks %}
                    {% for stock in essstocks %}
                    <tbody id="myTable">
                        <tr id="stock-{{stock.id}}">
                            
                            <td class="réf invData" name="Emplacement_SM" style="text-align: center;">
                                {{stock.Emplacement_SM}}</td>
                            <td class="réf invData" name="Réference" style="text-align: center;">{{stock.Reference}}
                            </td>
                            <td class="réf invData" name="Nombre_de_Bac" id="nc" style="text-align: center;">
                                {{stock.Nb_bacs}}</td>
                            <td class="réf invData" name="Date" style="text-align: center;">{{stock.Date_heure_entrée}}</td>
                            <td class="réf invData" name="Travée débord" style="text-align: center;">
                                {{stock.Travee_debord}}</td>
                            <td class="réf invData" name="code_condi" style="text-align: center;">
                                {{stock.Conditionnement_UC}}</td>
                            <td class="réf invData" name="piéce/UC" style="text-align: center;">{{stock.Qt_pieces_UC}}
                            </td>
                            <td class="réf invData" name="Appro" style="text-align: center;">{{stock.Appro}}</td>
                            <td class="réf invData" name="Fournisseur" style="text-align: center;">{{stock.Fournisseur}}
                            </td>
                            <td class="réf invData" name="CMJ" style="text-align: center;">{{stock.CMJ}}</td>
                            <td class="réf invData" name="FDS" style="text-align: center;">{{stock.FDS}}</td>
                            <td class="réf invData" name="FDS" style="text-align: center;">{{stock.Date_heure_sortie}}</td>
                        </tr>
                        {% endfor %}

                    </tbody>
                    {% else %}
                    <h3 style="color: crimson; text-align: center; "> Stock Débord Vide </h3>
                    {% endif %}


                </table>
            </div>
            
        </div>
    </div>
    <!--paination______________________________________________________-->

    <div class="container">
        {% if is_paginated %}
        <nav aria-label="Page navigation example">
            <ul class="pagination">

                {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
                </li>
                {% else %}
                <li class="disabled"><span class="page-link">&laquo;</span></li>
                {% endif %}
                {% for i in paginator.page_range %}
                {% if page_obj.number == i %}
                <li class="page-item" class="active"><span class="page-link">{{ i }} <span
                            class="sr-only">(current)</span></span></li>
                {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                {% else %}
                <li class="disabled">
                    <spa class="page-link">&raquo;</span>
                </li>
                {% endif %}

            </ul>
        </nav>
        {% endif %}
    </div>
    <!--end paination______________________________________________________-->

</div>





{% endblock %}
{% block javascript %}

<script type="text/javascript">



//imprimer
function imprimeres() {
        var printme = document.getElementById('histotableData');
        var wme = window.open("", ",width=900,height=700");
        wme.document.write(printme.outerHTML);
        wme.document.close;
        wme.focus();
        wme.print();
        wme.close();
}

</script>
{% endblock javascript %}

Stellantis_Djz/GA_UEP/templates/Error.html
{% extends "layout.html" %}
{% load static %}

{% block body %}
                <div class="container-fluid">
                    <div class="text-center mt-5">
                        <div class="error mx-auto" data-text="404">
                            <p class="m-0">404</p>
                        </div>
                    </div>
                </div>
            </div>
{% endblock %}

Stellantis_Djz/GA_UEP/templates/home.html
{% extends "layout.html" %}
{% load static %}

{% block body %}
<div class="text-center mt-5">
<h1 class="display-6">Bonjour à Stellantis   </h1>
</div>

<div class="container-fluid">
    <div class="text-center mt-5">
            <img src="{% static 'img/Homelogo.png' %}" class="img-fluid rounded" alt="Stellantis factory image">

    </div>
</div>
</div>

{% endblock %}
{% block javascript %}
<script>
    $(document).ready(function () {
        var supername = $("#supername").text();
       

        if (supername === 'Youssef' || supername ==='khalid') {
            console.log(supername)
           
        }
        else{
              $('#dasha').addClass('disabled');
            
        }
        

    });

</script>
{% endblock javascript %}

Stellantis_Djz/GA_UEP/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
  
    <title>Bord Kit - Stellantis</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css'%}">
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i">
    <link rel="stylesheet" href="{% static 'fonts/fontawesome-all.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/fontawesome5-overrides.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/datatable.css' %}">


</head>

<body id="page-top">
    <div id="wrapper">
        <nav class="navbar navbar-dark align-items-start sidebar sidebar-dark accordion bg-gradient-primary p-0"
            style="color: var(--blue);background: rgb(9,23,62);">
            <div class="container-fluid d-flex flex-column p-0"><a
                    class="navbar-brand d-flex justify-content-center align-items-center sidebar-brand m-0" href="#">
                    <div class="sidebar-brand-icon rotate-n-15"></div>
                    <div class="sidebar-brand-text mx-3"><span>Stellantis DJZ</span></div>
                </a>
                <hr class="sidebar-divider my-0">
                <ul class="navbar-nav text-light" id="accordionSidebar">
                    <li id="dash" class="nav-item"><a id="dasha" class="nav-link " href=" {% url 'GA_UEP:KPIS'%}"><i id="dashi"
                                class="fas fa-tachometer-alt"></i><span id="dashs">Dashboard</span></a></li>
                    <li class="nav-item">

                    </li>
                    <li class="nav-item"><a class="nav-link " href="{% url 'GA_UEP:crud_ajax'%}"><i class="fas fa-table"></i>&nbsp;Bord KIT</a>
                        <a class="nav-link " href="{% url 'GA_UEP:cross_dock'%}"><i class="fas fa-compress"></i>&nbsp;Cross DOCK</a>
                        <a class="nav-link " href="{% url 'GA_UEP:Mag_debord'%}"><i class="fas fa-store"></i>&nbsp;Mag Débord</a>

                        <a class="nav-link " href="{% url 'GA_UEP:FLC_A'%}"><i class="fas fa-hand-stop-o"></i>&nbsp;FLC</a>
                        <a class="nav-link " href="{% url 'GA_UEP:logout' %}"><i class="fas fa-close"></i>&nbsp;Log out</a>
                        
                        <a class="nav-link " href="#myModalinfo" data-toggle="modal" ><i class="fas fa-info"></i>&nbsp; How to use it</a>
                        
                            
                    </li>
                    <li class="nav-item"></li>
                    <li class="nav-item"></li>
                </ul>
                <div class="text-center d-none d-md-inline"><button class="btn rounded-circle border-0"
                        id="sidebarToggle" type="button"></button></div>
            </div>
        </nav>
        <div class="d-flex flex-column" id="content-wrapper">
            <div id="content">
                <nav class="navbar navbar-light navbar-expand bg-white shadow mb-4 topbar static-top" >
                    <div class="container-fluid"><button class="btn btn-link d-md-none rounded-circle mr-3"
                            id="sidebarToggleTop" type="button"><i class="fas fa-bars"></i></button>
                        <form
                            class="form-inline d-none d-sm-inline-block mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                            
                               
                            
                            
                        </form>
                       
                        <div>
                        
                           
                            
                            <h3 id="supername" style="text-align:right;float:right;" name="supername">{{ request.user.username }}</h3>
                             
                                                                                

                        </div>
                    </div>
                </nav>
<!-- modals pour changer le statut  ----------------------------------------------------------------------------------------------------------->
<div class="modal fade" id="myModalinfo" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="myModalLabel">Traitement Des Alertes</h4>
                <h4 id="m"></h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
            </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-12">
                            <div class="text-center">
                                <img src="{% static 'img/Flowchart.png' %}" class="rounded img-fluid " alt="Flowchart">
                            </div>
                        </div>
                       
                    </div>

                    

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>

           

        </div>
    </div>
</div>


                {% block body %}


                {% endblock %}

                <footer class="bg-white sticky-footer">
                    <div class="container my-auto">
                        <div class="text-center my-auto copyright"><span>Copyright © DJZ 2021</span></div>
                    </div>
                </footer>
            </div><a class="border rounded d-inline scroll-to-top" href="#page-top"><i class="fas fa-angle-up"></i></a>
        </div>
        
        <script src=" {% static 'js/jquery.min.js'%}"></script>
        <script src="{% static 'bootstrap/js/bootstrap.min.js'%}"></script>
        <script src="{% static 'js/chart.min.js'%}"></script>
        <script src="{% static 'js/bs-init.js'%}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.js"></script>
        <script src="{% static 'js/theme.js'%}"></script>
        <script src="{% static 'js/script.js'%}"></script>
        <script src="{% static 'js/jQ.js'%}"></script>
        <script src="{% static 'js/table.js'%}"></script>
        <script src="{% static 'js/swal.js'%}"></script>
        
        <!--
        <script src="{% static 'js/jQY.js'%}"></script>
        -->
        
        <script src="{% static 'js/jQf.js'%}"></script>
        <script src="{% static 'js/exportexcel.js'%}"></script>
        <script src="https://smtpjs.com/v3/smtp.js"></script>

        
        

        
        <link rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
        {% block javascript %}
    
        {% endblock javascript %}

        <!--
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.js"></script>
 -->


</body>

</html>